version: "3.8"
services: 
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes: 
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on: 
      - "flask-app"
  flask-app: 
    container_name: flask-app
    image: agray998/tag-me:latest
    build: .
    environment:
      YOUR_NAME: ${YOUR_NAME}